### ISSUE TITLE
Duplicate Candidate Terms

### ISSUE THREAD

**Issue by tsu-complete** [tsu-complete/taylorfit#50]
To initialize data (especially when preset by a former session) all parts (data, exponents, multiplicands, etc) are sent. Each of these triggers an update and re-computation slowing down the response time and flooding the interface. I would recommend a debounce to solve this (lodash has one) - don't trigger an update unless at least 30ms has passed between calls. (Can experiment with time, might even be able to make it 10ms or less, just has to be enough to not trigger when there is a mass update)

**Comment by patgrasso** [comment]
See 50533287b158bcedd087aa0e0c612964313096d6 and c1ccec6ad9f7be487ee9f9b0dab8ba76aab4bd1e. Instead of timing the calls, calls can be made to unsubscribe/subscribe to changes. Surrounding [the block that reads from localStorage and passes that info to the engine](https://github.com/tsu-complete/taylorfit/blob/master/interface/components/Model.coffee#L53-L70) with `unsubscribeToChanges()` and `subscribeToChanges()` calls prevents any of the intermediary changes from triggering a re-computation of the model or any candidates.
